### ISSUE TITLE
Stamina?

### ISSUE THREAD

**Issue by ff7man** [ergonomy-joe/ff7-chocobo#1]
https://github.com/ergonomy-joe/ff7-chocobo/blob/f4be8d1b6d412879ed9e17e5556458cb2994d012/NEWFF7/C_00772340.cpp#L87

https://github.com/ergonomy-joe/ff7-chocobo/blob/f4be8d1b6d412879ed9e17e5556458cb2994d012/NEWFF7/C_00772340.cpp#L108

these are unset, are they just a copy of maxstamina?

**Comment by ff7man** [comment]
additionally https://github.com/ergonomy-joe/ff7-chocobo/blob/f4be8d1b6d412879ed9e17e5556458cb2994d012/NEWFF7/C_00772340.cpp#L237
https://github.com/ergonomy-joe/ff7-chocobo/blob/f4be8d1b6d412879ed9e17e5556458cb2994d012/NEWFF7/C_00772340.cpp#L238
which I believe is just 0 for both

**Comment by ergonomy-joe** [comment]
If I understand what you mean, this is not an issue.
`a = b = c;` is a legit C idiom. I just decided to insert a newline after `a =` for "readability".

**Comment by ff7man** [comment]
ahhhh ty
